Numpy Array operation in 1D
Operation                  | Method / Function                  | Description
---------------------------|------------------------------------|----------------------------------------------------------
Basic Slicing               | arr[start:end]                     | Extracts elements from index `start` to `end-1`.
Slicing with Step           | arr[start:end:step]                 | Extracts elements with a given step size.
Negative Indexing           | arr[-n:]                           | Selects last `n` elements.
Reverse (Slicing)           | arr[::-1]                          | Reverses the array using slicing.
Reverse with Step           | arr[::-step]                       | Reverses array and selects elements with step size.
Inbuilt Reverse (NumPy)     | np.flip(arr)                       | Reverses array using NumPy's built-in function.
Sort Ascending (NumPy)      | np.sort(arr)                       | Sorts elements in ascending order.
Sort Descending (NumPy)     | np.sort(arr)[::-1]                  | Sorts in ascending order, then reverses for descending.
Sort Descending (List)      | list.sort(reverse=True)            | Python list method to sort in descending order (not NumPy).
Difference: Reverse vs Sort | Reverse changes only positions,    | Sorting rearranges elements based on their values.
                            | values remain the same.            |


In [ ]:
import numpy as np

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

print("Original array:     ", arr)

# Basic slicing
print("First 5 elements:   ", arr[:5])      # index 0 to 4
print("Every 2nd element:  ", arr[::2])     # step of 2
print("Middle slice:       ", arr[3:8])     # index 3 to 7

# Negative indexing
print("Last 3 elements:    ", arr[-3:])     # last three elements
print("All except last 3:  ", arr[:-3])     # everything except last three

# Reversing
print("Reversed array:     ", arr[::-1])    # reverse using slicing
print("Reverse every 2nd:  ", arr[::-2])    # reverse, step 2

# Inbuilt reverse
print("Inbuilt np.flip():  ", np.flip(arr)) # reverse using NumPy function


Numpy Operation In 2D

In [ ]:
import numpy as np

# Create a sample 2D array
arr = np.array([
    [9, 2, 7],
    [4, 5, 1],
    [8, 3, 6]
])

print("Original Array:\n", arr)

# 1. Basic slicing
print("\nFirst 2 rows:\n", arr[:2, :])
print("First 2 columns:\n", arr[:, :2])

# 2. Slicing with step
print("\nEvery 2nd row:\n", arr[::2, :])
print("Every 2nd column:\n", arr[:, ::2])

# 3. Negative indexing
print("\nLast row:\n", arr[-1:, :])
print("Last column:\n", arr[:, -1:])

# 4. Reverse
print("\nReverse both rows & columns:\n", arr[::-1, ::-1])
print("Reverse rows only (flipud):\n", np.flipud(arr))
print("Reverse columns only (fliplr):\n", np.fliplr(arr))
print("Reverse using np.flip (all axes):\n", np.flip(arr))

# 5. Sorting
# axis=0 → operation is done down the rows, so it affects columns.
# axis=1 → operation is done across the columns, so it affects rows.
print("\nSort by rows ascending:\n", np.sort(arr, axis=1))
print("Sort by columns ascending:\n", np.sort(arr, axis=0))
print("Sort by rows descending:\n", np.sort(arr, axis=1)[:, ::-1])
print("Sort by columns descending:\n", np.sort(arr, axis=0)[::-1, :])


Filter & Mask
| Concept       | Meaning                                                         | Example         |
| ------------- | --------------------------------------------------------------- | --------------- |
| **Mask**      | Boolean array indicating which elements meet a condition        | `arr > 30`      |
| **Filtering** | Using the mask to get only the elements that meet the condition | `arr[arr > 30]` |



In [ ]:
import numpy as np

arr2d = np.array([[5, 15, 25],
                  [35, 45, 55],
                  [65, 75, 85]])

# Filtering: Get elements greater than 40
filtered_2d = arr2d[arr2d > 40]

# Mask: Boolean array for the same condition
mask_2d = arr2d > 40


print("\n2D Array:\n", arr2d)
print("Filtered (2D):", filtered_2d)
print("Mask (2D):\n", mask_2d)
print("Mask ()2D:\n", arr2d[mask_2d])


| Feature                   | Description                                               | Example / Notes                                    |
|---------------------------|-----------------------------------------------------------|---------------------------------------------------|
| np.where(condition)       | Returns indices where the condition is True              | `arr = np.array([5,10])` <br> `np.where(arr>5)` <br> Output: `(array([1]),)` |
| np.where(condition, x, y) | Creates a new array with values x if True, y if False    | `arr = np.array([10,20])` <br> `np.where(arr>15,1,0)` <br> Output: `[0 1]` |
| Multiple Conditions       | Nest `np.where()` for multiple conditions               | `np.where(arr<20,'Low', np.where(arr<=40,'Medium','High'))` <br> Output: `['Low','Medium']` |
| np.where without array    | Use on generated sequences like `np.arange()`           | `nums = np.arange(5)` <br> `np.where(nums%2==0,'Even','Odd')` <br> Output: `['Even','Odd','Even','Odd','Even']` |
| Filtering indices         | Returns array of indices satisfying the condition        | `np.where(arr>10)` <br> Output: `(array([2,3]),)` |
| Key Points                | 1. `np.where` → arrays <br> 2. Nest for multiple conditions <br> 3. Can generate arrays from scratch <br> 4. Can be used for filtering/masking | - |


In [ ]:
import numpy as np

# 1. Basic np.where – Get indices
arr = np.array([5, 10, 15, 20])
indices = np.where(arr > 10)
print(indices)
# Output: (array([2, 3]),)

# 2. Basic np.where – Conditional array creation
new_arr = np.where(arr > 15, 1, 0)
print(new_arr)
# Output: [0 0 0 1]

# 3. np.where with strings / labels
labels = np.where(arr < 10, 'Low', 'High')
print(labels)
# Output: ['Low' 'High' 'High' 'High']

# 4. Multiple conditions (nested np.where)
multi_labels = np.where(arr < 10, 'Very Low',
                        np.where(arr <= 15, 'Low', 'High'))
print(multi_labels)
# Output: ['Very Low' 'Low' 'Low' 'High']

# 5. np.where without existing array
nums = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
even_odd = np.where(nums % 2 == 0, 'Even', 'Odd')
print(even_odd)
# Output: ['Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd']

# 6. Filtering array using np.where
filtered_indices = np.where(nums > 5)
print(filtered_indices)
# Output: (array([6, 7, 8, 9]),)

# ==============================
# Key Points:
# 1. np.where(condition) → returns indices
# 2. np.where(condition, x, y) → creates new array
# 3. Can nest np.where() for multiple conditions
# 4. Can use with generated arrays (np.arange, etc.)
# ==============================


Operation on array

| Method                       | Description                                      | Example / Notes |
|-------------------------------|-------------------------------------------------|----------------|
| `np.append(array, values)`    | Adds elements at the end, returns new array    | `arr = np.array([1,2,3])` <br> `new_arr = np.append(arr, [4,5])` <br> Output: `[1 2 3 4 5]` |
| `np.insert(array, index, values)` | Insert element at specific index             | `np.insert(arr, 1, 10)` <br> Output: `[1 10 2 3]` |
| `np.concatenate((arr1, arr2))` | Join two arrays                                | `arr1 = [1,2]; arr2=[3,4]` <br> Output: `[1 2 3 4]` |
| `np.vstack((arr1, arr2))`     | Stack arrays vertically (row-wise)             | `np.vstack((arr1, arr2))` → `[[1 2] [3 4]]` |
| `np.hstack((arr1, arr2))`     | Stack arrays horizontally (column-wise)       | `np.hstack((arr1, arr2))` → `[1 2 3 4]` |

In [ ]:
import numpy as np

# 1. np.append(array, values) – Add elements at the end
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5])
print("np.append:", new_arr)
# Output: [1 2 3 4 5]

# 2. np.insert(array, index, values) – Insert element at specific index
arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, 10)
print("np.insert:", new_arr)
# Output: [1 10 2 3]

# 3. np.concatenate((arr1, arr2)) – Join two arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
new_arr = np.concatenate((arr1, arr2))
print("np.concatenate:", new_arr)
# Output: [1 2 3 4]

# 4. np.vstack((arr1, arr2)) – Stack arrays vertically (row-wise)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
new_arr = np.vstack((arr1, arr2))
print("np.vstack:\n", new_arr)
# Output:
# [[1 2]
#  [3 4]]

# 5. np.hstack((arr1, arr2)) – Stack arrays horizontally (column-wise)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
new_arr = np.hstack((arr1, arr2))
print("np.hstack:", new_arr)
# Output: [1 2 3 4]


Mathematical Operation
# NumPy Cheatsheet – Arrays, Conditional Arithmetic & Multiplication

| Concept                        | Theory / Rules                                                                                 | Notes / Examples |
|--------------------------------|-------------------------------------------------------------------------------------------------|-----------------|
| **Adding Elements**             | `np.append`, `np.insert`, `np.concatenate`, `np.vstack`, `np.hstack` add or stack arrays.      | New arrays returned; original unchanged |
| **Conditional Arithmetic**      | `np.where(condition, x, y)` applies arithmetic based on condition.                             | Logical AND `&`, OR `|` allowed; element-wise operations |
| **Broadcasting**                | Arrays of different shapes can be used in element-wise ops if trailing dimensions match or one is 1. | Smaller arrays are “stretched” automatically |
| **Inner Dimension Rule**        | For matrix multiplication `A(m×n) @ B(p×q)`, n must equal p; result shape = (m×q).           | Inner dims = columns of A = rows of B; outer dims = result shape |
| **Element-wise Multiplication** | `*` operator multiplies arrays element by element; broadcasting can allow different shapes.   | Shapes must be compatible or broadcastable |
| **Matrix Multiplication**       | `@` or `np.dot(A, B)` multiplies matrices following inner dimension rule.                      | Use `.reshape()` if shapes incompatible |


In [ ]:
import numpy as np

# 1. Adding / Stacking Arrays
arr = np.array([1,2,3])
print("np.append:", np.append(arr,[4,5]))               # [1 2 3 4 5]
print("np.insert:", np.insert(arr,1,10))               # [1 10 2 3]

arr1 = np.array([1,2])
arr2 = np.array([3,4])
print("np.concatenate:", np.concatenate((arr1,arr2))) # [1 2 3 4]
print("np.vstack:\n", np.vstack((arr1,arr2)))         # [[1 2] [3 4]]
print("np.hstack:", np.hstack((arr1,arr2)))           # [1 2 3 4]

# 2. Conditional Arithmetic
arr = np.array([10,20,30,40])
print("Single condition np.where:", np.where(arr>25, arr*2, arr+5)) # [15 25 60 80]
print("Multiple condition np.where:", np.where((arr>15)&(arr<=30), arr*3, arr+2)) # [12 60 32 42]

# 3. Element-wise Multiplication with Broadcasting
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10,20,30]])
print("Element-wise with broadcasting:\n", A*B)

# 4. Matrix Multiplication (Inner Dimension Rule)
A = np.array([[1,2,3],[4,5,6]])  # 2x3
B = np.array([[7,8],[9,10],[11,12]])  # 3x2
C = A @ B
print("Matrix multiplication @:\n", C)

# 5. Example of incompatible shapes for element-wise multiplication
try:
    a = np.array([1,2,3])
    b = np.array([[1,2],[3,4]])
    print(a+b)
except ValueError as e:
    print("Error (incompatible shapes):", e)


np.dot() vs @
| Operator / Function | Type of Multiplication            | Requirement / Rule                                                                 | Result Shape / Notes                           |
|--------------------|---------------------------------|----------------------------------------------------------------------------------|-----------------------------------------------|
| `*`                | Element-wise multiplication      | Arrays must be same shape or broadcastable                                        | Each element multiplied individually          |
| `@` or `np.dot()`  | Matrix multiplication (dot)      | Inner dimension rule: columns of first matrix = rows of second matrix            | Result shape = (rows of first × columns of second) |


In [ ]:
import numpy as np

# Arrays
A = np.array([[1,2,3],
              [4,5,6]])  # Shape: 2x3
B = np.array([[10,20,30],
              [40,50,60]])  # Shape: 2x3

# 1. Element-wise multiplication
elem_mult = A * B
print("Element-wise multiplication (*):\n", elem_mult)
# Output:
# [[ 10  40  90]
#  [160 250 360]]

# 2. Matrix multiplication (@)
C = np.array([[1,2,3],
              [4,5,6]])    # 2x3
D = np.array([[7,8],
              [9,10],
              [11,12]])    # 3x2
mat_mult = C @ D
print("\nMatrix multiplication (@):\n", mat_mult)
# Output:
# [[ 58  64]
#  [139 154]]


# Step-by-Step Matrix Multiplication (A @ B)

Let
\[
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad
B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}
\]

---

### Step 1: First element \(C[0,0]\)

\[
C[0,0] = (1*7) + (2*9) + (3*11)
\]

Calculation:
\[
1*7 = 7,\quad 2*9 = 18,\quad 3*11 = 33
\]
\[
C[0,0] = 7 + 18 + 33 = 58
\]

---

### Step 2: First row, second column \(C[0,1]\)

\[
C[0,1] = (1*8) + (2*10) + (3*12)
\]
\[
= 8 + 20 + 36 = 64
\]

---

### Step 3: Second row, first column \(C[1,0]\)

\[
C[1,0] = (4*7) + (5*9) + (6*11)
\]
\[
= 28 + 45 + 66 = 139
\]

---

### Step 4: Second row, second column \(C[1,1]\)

\[
C[1,1] = (4*8) + (5*10) + (6*12)
\]
\[
= 32 + 50 + 72 = 154
\]

---

### ✅ Final Result

\[
C = \begin{bmatrix} 58 & 64 \\ 139 & 154 \end{bmatrix}
\]
